name: 'discord-bot'
description: 'This GitHub Action sends fancy and more meaningful discord messages for your commits. It includes Test results and coverage.'
author: mansuetopaiva
branding:
  icon: message-square
  color: gray-dark
inputs:
  args:
    description: 'The message to display in the Discord message.'
    required: true
     avatar:
    description: "An avatar for the message"
