name: discord message
on: [push]
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main 
        with:
         id: ${{ secrets.DISCORD_WEBHOOK }}
         token: ${{ secrets.DISCORD_TOKEN }}
         repo_name: bot-discord