name: discord message
on: [push]
jobs:
  pull-request:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      run: node ../../index.js
    env:
       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
       args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'