name: discord message
on: [push]
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Discord Webhook

        uses: mansuetopaiva/discord-bot@test 
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}