name: Discord Commits
on: [push]
jobs:
  git:
    name: Git Commits
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Discord Webhook
      uses: ./
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        color: 0000FF
        username: "Github"
        avatar: "https://github.com/mansuetopaiva/MansuetoPaiva/assets/133207241/18856d09-294a-4b83-8755-4cd5c10e2565"
