name: Discord Commits

on: [push]

jobs:
  git:
    name: Git Commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Discord Webhook
        uses: mansuetopaiva/discord-bot@test
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: 12B92E
          
          # uses: mansuetopaiva/discord-bot@test 