name: Discord Commits
on: [push]
jobs:
  git:
    name: Git Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: C0D9D9
          # 12B92E
